package com.leetcode.accepted;

/**
 * <h1>389. Find The Difference (E)</h1>
 * <p>
 * Given two strings s and t which consist of only lowercase letters.<br>
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position. <br>
 * Find the letter that was added in t.<br>
 * </p>
 * <p>
 * <b>Example</b>
 * </p>
 * 
 * <pre>
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * </pre>
 * 
 * @author Sumit
 *
 */
public class FindTheDifference {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		FindTheDifference ftd = new FindTheDifference();
		System.out.println(ftd.findTheDifference("abcd", "abcde")); // e
		System.out.println(ftd.findTheDifference("", "k")); // k
		System.out.println(ftd.findTheDifference("elas", "elsas")); // s
	}

	/**
	 * LeetCode accepted solution for Find The Difference
	 * 
	 * @param s
	 *            the first string
	 * @param t
	 *            the second string
	 * @return the extra character
	 */
	public char findTheDifference(String s, String t) {
		if (null == s || null == t) {
			return '\0';
		}
		if ("".equals(s) && !"".equals(t)) {
			return t.charAt(0);
		}
		if ("".equals(t) && !"".equals(s)) {
			return s.charAt(0);
		}
		if (s.length() > t.length()) {
			for (char ch : s.toCharArray()) {
				if (!t.contains(String.valueOf(ch))) {
					return ch;
				} else {
					t.replaceFirst(String.valueOf(ch), "");
				}
			}
		} else {
			for (char ch : t.toCharArray()) {
				if (!s.contains(String.valueOf(ch))) {
					return ch;
				} else {
					s = s.replaceFirst(String.valueOf(ch), "");
				}
			}
		}
		return '\0';
	}

}
